language: python
python:
  - "3.6"
  # PyPy versions

# command to install dependencies


install:
  - sudo apt-get install xvfb
  - pip3 install xvfbwrapper
  - pip3 install pyqt5
  - pip3 install opencv-python
  - pip3 install requests


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start



script:
  - xvfb-run --auto-servernum --server-args="-screen 0 1280x760x24" python3 test.py
